### ISSUE TITLE
Index Not Found Bug?

### ISSUE THREAD

**Issue by john-klingner** [correlllab/cu-droplet#18]
When there are two Hydrogen atoms, bonded, and then an oxygen arrives:

The Oxygen gets IMR flag 'n', then prints 'blarg', I think because other_orbs is 0, and so doesn't do anything.

The Hydrogen, meanwhile, is getting IMR flag 'f'. It then acquires Oxygen's base valence shell, (which doesn't change anything since the oxygen hasn't bonded to anyone yet). Then it calls formBond, which goes through but (because this Hydrogen is still bonded to the other Hydrogen), can't find an index for add_to_bonded_atoms, and so the Oxygen doesn't get bonded to.

So - yeah! Not sure exactly where the bug is but I think there is one.

**Comment by Audrey-Randall** [comment]
Okay, I can come in in an hour and look
